### ISSUE TITLE
Client API is not supported.

### ISSUE THREAD

**Issue by cch1** [avescodes/conformity#40]
The Datomic Client API does not support installing database functions.  Yet clients using the Client API are just as likely to benefit conforming the database.

I appreciate that this is a difficult problem in the general case as the database fn being created is central to the transactional nature of conforming the schema.

Would it be possible to create a "port" of the bulk of conformity to use the Client API?  There would still need to be a very small function to install the database function, but that could be a one-time task.  And for ad-hoc usage, there is obviously a loophole for getting the fn installed on initialization.

Perhaps this issue can serve as a starting point to discuss ways of working around this fundamental problem.

**Comment by conan** [comment]
It looks like transaction functions in cloud can be achieved using [Ions](https://docs.datomic.com/cloud/transactions/transaction-functions.html#custom)

**Comment by cch1** [comment]
Yep, Ions seems like it would handle the db fn.  Installation of the function will be more complex, but once available conformity's model should still work.  Which puts more emphasis on having a "port" that supports the client API.

**Comment by rkneufeld** [comment]
I’m not much into Datomic nowadays. If a few folks wanted to take the rein and implement new features like above I’d be happy to hand things over

**Comment by iku000888** [comment]
Conformity heavily depends on peer api specifics for implementation, so from my point of view this is a won't fix.
